balance_weight: false
batch_size: 1
beta_max: 0.01
beta_min: 5.0e-05
cos_epoch: 22
cutoff_date: '2024-03-01'
d_clamp: 30
data_std: 35
decoder_batch_size: 48
decoder_dim: 768
decoder_nhead: 12
decoder_num_layers: 12
distogram_weight: 0.03
epochs: 36
folding_blocks: 24
grad_clip: 10.0
gradient_accumulation_steps: 1
learning_rate: 0.0005
loss_power_scale: 0
max_cycles: 4
max_len: 384
val_max_len: 768
max_len_filter: 9999999
min_len_filter: 10
mixed_precision: "bf16"
model_config_path: ../working/configs/pairwise.yaml
n_times: 1000
pretrained_weight_path: ../pytorch_model_fsdp.bin
reload_model_path: none
reload_optimizer_path: none
sampler_clip_max: 256
sampler_clip_min: 256
seed: 0
structural_violation_epoch: 50
test_cutoff_date: '2024-05-01'
trunk_dropout: 0.0
trunk_grad: false
val_n_steps: 100
warmup_steps: 600
weight_decay: 0.0
