balance_weight: false
batch_size: 1
beta_max: 0.01
beta_min: 5.0e-05
cos_epoch: 5
cutoff_date: '2024-03-01'
d_clamp: 30
data_std: 17
decoder_batch_size: 48
decoder_dim: 768
decoder_nhead: 12
decoder_num_layers: 24
distogram_weight: 0.03
epochs: 70
grad_clip: 10.0
gradient_accumulation_steps: 1
learning_rate: 8.0e-4  # Increased learning rate
loss_power_scale: 0.0
max_cycles: 1
max_len: 384
max_len_filter: 9999999
min_len_filter: 10
mixed_precision: bf16
model_config_path: ../working/configs/pairwise.yaml
n_times: 1000
pretrained_weight_path: ../../8m_exps/test32/models/epoch_0/pytorch_model_fsdp.bin
seed: 0
structural_violation_epoch: 50
test_cutoff_date: '2024-05-01'
val_n_steps: 100
warmup_steps: 20
weight_decay: 0.0
trunk_grad: false
trunk_dropout: 0.0

#sampler config
sampler_clip_max: 256
sampler_clip_min: 256

#restart model training
reload_model_path: 'weights/stage1_bigger_lr.yaml_RibonanzaNet_3D.pt'
reload_optimizer_path: 'weights/stage1_bigger_lr.yaml_RibonanzaNet_3D_optimizer.pt'