balance_weight: false
batch_size: 1
beta_max: 0.01
beta_min: 5.0e-05
cos_epoch: 5
cutoff_date: '2021-06-01'
d_clamp: 10
data_std: 35
decoder_batch_size: 32
decoder_dim: 768
decoder_nhead: 12
decoder_num_layers: 12
distogram_weight: 0.03
epochs: 36
grad_clip: 10.0
gradient_accumulation_steps: 1
learning_rate: 0.0002
loss_power_scale: 1.0
max_cycles: 1
max_len: 600
max_len_filter: 9999999
min_len_filter: 10
mixed_precision: bf16
model_config_path: ../working/configs/pairwise.yaml
n_times: 1000
pretrained_weight_path: ../../8m_exps/test32/models/epoch_0/pytorch_model_fsdp.bin
seed: 0
structural_violation_epoch: 50
test_cutoff_date: '2022-05-01'
val_n_steps: 100
weight_decay: 0.0
